[package]
name = "hash-killer"
version = "0.1.1"
edition = "2021"

[features]
default = ["core"]
core = []

[dependencies]

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
blake3 = { version = "1.8.5", features = ["rayon", "mmap"] }
jwalk = "0.8.1"
md-5 = "0.11.0"
rayon = "1.12.0"
rusqlite = { version = "0.39.0", features = ["bundled"] }
same-file = "1.0.6"
serde = { version = "1.0.228", features = ["derive"] }
sha2 = "0.11.0"
