[package]
name = "hash-killer-desktop"
version = "0.1.1"
edition = "2021"

[lib]
name = "hash_killer_desktop_lib"
crate-type = ["rlib"]

[[bin]]
name = "hash-killer-desktop"
path = "src/main.rs"

[build-dependencies]
tauri-build = { version = "2.6.1", features = [] }

[dependencies]
hash-killer = { path = "../../..", default-features = false, features = ["core"] }
rfd = "0.17.2"
serde = { version = "1.0.228", features = ["derive"] }
tauri = { version = "2.11.1", features = [] }
